### ISSUE TITLE
Stack generates a lot of extra Markup

### ISSUE THREAD

**Issue by smksnutmeg** [seek-oss/braid-design-system#386]
I watched the conference talk of Mark last night and found it very interesting. One flag to me was that Stack wraps a Div for every child. Seems like an overload of unnecessary markup. The approach in our Design system was to apply a default stack (1 rem down) to our Atomic components. With a BEM modifier of $--no-stack as an optional prop `noStack`

If we need spacing to be grouped, we use a `Block` and allow that to have a variety of stack down sizes.

https://github.com/seek-oss/braid-design-system/blob/master/lib/components/Stack/Stack.tsx

**Comment by maraisr** [comment]
I'd second this motion. But you have to realize as well, that Seek is a job site, their site/sites don't have a lot of DOM as it is, so the DX outweighs the cost of extraneous DOM.

**Comment by markdalgleish** [comment]
Thanks for raising this question. It's definitely a valid concern.

An alternative approach would be to use a selector like `> *:not(:first-child)` to add top padding to all child nodes via CSS, but there are a couple of tradeoffs here:

- This will create additional CSS, rather than re-using existing padding classes from `Box`. We'd have to create a separate atomic class for every item in our space scale, for each of our viewport sizes.
- Arguably creates a leaky abstraction if a child component returns a fragment because the spacing will impact the child nodes of another component.

However, I can definitely see an argument that this tradeoff is worth it:

- If `Stack` is used a lot in a single page, the extra CSS will be smaller than the additional HTML.
- You could alternatively argue that _not_ spacing out fragmented content is actually a bug. Currently, if a component returns a fragment and you want to maintain the correct spacing, you have to return a `Stack` instead. We've run into this a bit, and in practice it kinda feels like a poor separation of concerns.

On reflection, I can see us changing approaches here, but we'll discuss this a bit further internally.

**Comment by maraisr** [comment]
and from your internal findings, would you openly share it? I tend to learn a lot from seeing your things.

**Comment by LasseRafn** [comment]
(Disclaimer: I made a Vue-port of Braid but point is the same) 

I have yet to encounter this being a major thing. Obviously I would love to not have those divs, but extra bytes + CPU overhead is slim to none (in our situation)

I can imagine if you use lots and lots of stacks, with hundreds of elements each it would "add up" but there are so many other optimizations in peoples codebases, to do before this one. 

I'd file this under "micro optimization" — and not act on it unless a solution comes that has no tradeoffs to dev-experience.

Just my 2 cents

**Comment by palashkaria** [comment]
@LasseRafn out of curiosity, is that Vue-port available somewhere? Did you change anything in that? Would love to take a look if possible! ✨

**Comment by LasseRafn** [comment]
Still toying around, mostly have just made the layout components (not buttons etc.)

Will be making it available soon, can shoot you a link by then?

Tried to make api, dom structure and styling more or less identical

**Comment by stephan281094** [comment]
Just curious, wouldn't it be possible to use CSS grid for stacks? You could use `grid-gap` for spacing, which automatically takes care of the last child. Browser support seems acceptable too: https://caniuse.com/#search=css%20grid.

**Comment by mattsjones** [comment]
We currently still support Safari 8+ which blocks any grid usage all together.

**Comment by gnapse** [comment]
I arrived here looking if this was also a concern for others, as it seems to be the case. We've been inspired by Braid and developed our own version of these components in a more rudimentary way (using css modules and more repetitive CSS for now, we may improve it internally later on with vanilla-extract for instance).

We're thinking of going ahead and removing the extra elements both in `Stack` and `Inline`. Aside from the potential issues that have already been discussed here, I will add a couple of points that I'm concerned about:

1. When used with `component="ul"` it is the consumer's responsibility to provide the `li` elements. Not abig deal, just pointing it out.
2. When the `dividers` is set and the outer `Stack` has `component="ul"` set. Then the dividers will be siblings of the `li` elements, which I guess it's a bigger deal.

An alternative I thought of is to keep the feature of adding the extra elements, but only if the conditions in the two points above are met. For the moment we will not do it, but maybe. If these issues become a problem in practice.

---

Other thing we've done to reduce the need for using extra elements is to allow in all layout components (`Stack`, `Inline`, `Columns`) to use some of the props in `Box` that do not affect layout (e.g. borders, padding, etc). This way when we need a stack to also figure a certain background or an inner padding, we apply it directly to it. If I recall correctly, in Braid this is not the case.

**Comment by michaeltaranto** [comment]
At this point is unavoidable complexity for us and our requirements. I'm going to close the issue as its not likely something that will change until flex-gap support aligns with our browser policy.
